project:
  type: website
  output-dir: _site
  render:
    - "index.qmd"
    - "maths appliquées/*.md"
    - "probabilités/*.md"
    - "metacrisis/*.md"
    - "!pronostics/"

website:
  title: "chekpoint-89"
  page-navigation: true
  bread-crumbs: true
  navbar:
    left:
      - href: index.qmd
        text: Mes notes
  sidebar:
    style: docked
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Accueil
      - section: "Maths appliquées"
        collapsed: true
        contents:
          - href: maths appliquées/1. representation-geometrie-et-resolution.md
            text: "1. Representation geometrie et resolution"
          - href: maths appliquées/2. mesurer-la-proximite.md
            text: "2. Mesurer la proximite"
          - href: maths appliquées/3. projection-orthogonale-et-produit-scalaire.md
            text: "3. Projection orthogonale et produit scalaire"
          - href: maths appliquées/4. variables-aléatoires.md
            text: "4. Variables aleatoires"
          - href: maths appliquées/5. distance-hyperplan-lp.md
            text: "5. Distance à un hyperplan en norme ℓp"
          - href: maths appliquées/6. application-de-dualite-et-perte-orthogonalite.md
            text: "6. Application de dualité et perte d'orthogonalité"
      - section: "Probabilités"
        collapsed: true
        contents:
          - href: probabilités/0000. syllabus.md
            text: Syllabus
          - href: probabilités/0100. tribus-et-espaces-mesurables.md
            text: "0100. Tribus et espaces mesurables"
          - href: probabilités/0110. lemme-de-factorisation-doob.md
            text: "0110. Lemme de factorisation de Doob"
          - href: probabilités/0120. nombres-transfinis-et-ordinaux.md
            text: "0120. Nombres transfinis et ordinaux"
          - href: probabilités/0121. strictité-de-la-hiérarchie-borélienne.md
            text: "0121. Strictité de la hiérarchie borélienne"
          - href: probabilités/0200.mesures-et-probabilités.md
            text: "0200. Mesures et probabilités"
      - section: "Meaning Crisis"
        collapsed: true
        contents:
          - href: metacrisis/1.md
            text: "1. All Is Fucked Up"
          - href: metacrisis/2.md
            text: "2. Traditions & Meaning"
          - href: metacrisis/3.md
            text: "3. Consciousness"

format:
  html:
    from: markdown+hard_line_breaks
    toc: true
    toc-depth: 4
    number-sections: false
    html-math-method: mathjax
    theme: cosmo