project:
  type: website
  output-dir: _site
  render:
    - "index.qmd"
    - "polyglotte/**/*.md"
    - "essays/*.md"
    - "maths appliquées/*.md"
    - "probabilités/*.md"
    - "machine_learning/**/*.md"
    - "metacrisis/*.md"
    - "cheat sheets/*.md"
    - "economics/micro-economics/*.ipynb"
    - "!economics/micro-economics/micro.ipynb"
    - "!pronostics/"

website:
  title: "chekpoint-89"
  page-navigation: true
  bread-crumbs: true
  navbar:
    left:
      - href: index.qmd
        text: Mes notes
  sidebar:
    style: docked
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Accueil
      - section: "Polyglotte"
        collapsed: true
        contents:
          - href: polyglotte/[Russian]-gunpowder-how-it-changed-history.md
            text: "Порох: как он изменил историю"
          - section: "Die verlorene Ehre der Katarina Blum"
            collapsed: true
            contents:
              - href: "polyglotte/[German]-Die verlorene Ehre der Katarina Blum/1.md"
                text: "1"
      - section: "Essays"
        collapsed: true
        contents:
          - href: essays/les-mathematiques-par-le-geste.md
            text: "Les mathematiques par le geste"
          - href: essays\demontrer-n_est-pas-situer.md
            text: "Démontrer n'est pas situer"
          - href: essays\software-engineering.md
            text: "Manifesto for Intelligible Software Engineering"
      - section: "Cheat sheets"
        collapsed: true
        contents:
          - href: cheat sheets/inegalites-fondamentales.md
            text: "Inégalités fondamentales"
      - section: "Maths appliquées"
        collapsed: true
        contents:
          - href: maths appliquées/1. representation-geometrie-et-resolution.md
            text: "1. Representation geometrie et resolution"
          - href: maths appliquées/2. mesurer-la-proximite.md
            text: "2. Mesurer la proximite"
          - href: maths appliquées/3. projection-orthogonale-et-produit-scalaire.md
            text: "3. Projection orthogonale et produit scalaire"
          - href: maths appliquées/4. variables-aléatoires.md
            text: "4. Variables aleatoires"
          - href: maths appliquées/5. distance-hyperplan-lp.md
            text: "5. Distance à un hyperplan en norme ℓp"
          - href: maths appliquées/6. application-de-dualite-et-perte-orthogonalite.md
            text: "6. Application de dualité et perte d'orthogonalité"
      - section: "Probabilités"
        collapsed: true
        contents:
          - href: probabilités/0000. syllabus.md
            text: Syllabus
          - href: probabilités/0100. tribus-et-espaces-mesurables.md
            text: "0100. Tribus et espaces mesurables"
          - href: probabilités/0110. lemme-de-factorisation-doob.md
            text: "0110. Lemme de factorisation de Doob"
          - href: probabilités/0120. nombres-transfinis-et-ordinaux.md
            text: "0120. Nombres transfinis et ordinaux"
          - href: probabilités/0121. strictité-de-la-hiérarchie-borélienne.md
            text: "0121. Strictité de la hiérarchie borélienne"
          - href: probabilités/0200.mesures-et-probabilités.md
            text: "0200. Mesures et probabilités"
      - section: "Machine learning"
        collapsed: true
        contents:
          - href: machine_learning/clustering/clustering_metrics.md
            text: "Évaluer un clustering"
          - href: machine_learning/estimation/linear_regression.md
            text: "Convergence de vues"
      - section: "Meaning crisis"
        collapsed: true
        contents:
          - href: metacrisis/1.md
            text: "1. All Is Fucked Up"
          - href: metacrisis/2.md
            text: "2. Traditions & Meaning"
          - href: metacrisis/3.md
            text: "3. Consciousness"
      - section: "Microéconomie"
        collapsed: true
        contents:
          - href: economics/micro-economics/micro-00-intro.ipynb
            text: "Introduction"
          - href: economics/micro-economics/micro-01-motivation.ipynb
            text: "00. Motivation"
          - href: economics/micro-economics/micro-02-preferences.ipynb
            text: "01. Préférences"
          - href: economics/micro-economics/micro-03-utilite-indifference.ipynb
            text: "02. Utilité et indifférence"
          - href: economics/micro-economics/micro-04-tms-preferences.ipynb
            text: "03. TMS et formes de préférences"
          - href: economics/micro-economics/micro-05-contrainte-budgetaire.ipynb
            text: "04. Contrainte budgétaire"
          - href: economics/micro-economics/micro-06-choix-optimal.ipynb
            text: "05. Choix optimal"
          - href: economics/micro-economics/micro-07-demande-individuelle.ipynb
            text: "06. Demande individuelle"
          - href: economics/micro-economics/micro-08-elasticites.ipynb
            text: "07. Élasticités"
          - href: economics/micro-economics/micro-09-effets-prix-revenu-substitution.ipynb
            text: "08. Effets prix, revenu et substitution"
          - href: economics/micro-economics/micro-10-types-de-biens.ipynb
            text: "09. Types de biens"
          - href: economics/micro-economics/micro-11-preferences-revelees.ipynb
            text: "10. Préférences révélées"
          - href: economics/micro-economics/micro-12-travail-loisir.ipynb
            text: "11. Arbitrage travail-loisir"
          - href: economics/micro-economics/micro-13-choix-intertemporel.ipynb
            text: "12. Choix intertemporel"
          - href: economics/micro-economics/micro-14-capital-humain.ipynb
            text: "13. Capital humain"
          - href: economics/micro-economics/micro-15-risque.ipynb
            text: "14. Risque"
          - href: economics/micro-economics/micro-99-annexes.ipynb
            text: "99. Annexes"

execute:
  echo: false

format:
  html:
    from: markdown+hard_line_breaks
    toc: true
    toc-depth: 4
    number-sections: false
    html-math-method: mathjax
    theme: cosmo